[[redirects]]
  from = "/website"
  to = "/website.html"
  status = 200

[[redirects]]
  from = "/public"
  to = "/website.html"
  status = 200

[[redirects]]
  from = "/sales-hub"
  to = "/sales-hub.html"
  status = 200

[[redirects]]
  from = "/business-hub"
  to = "/business-hub.html"
  status = 200

[[redirects]]
  from = "/platform"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/hub"
  to = "/business-hub.html"
  status = 200
