[[redirects]]
  from = "/"
  to = "/website.html"
  status = 200
  force = true

[[redirects]]
  from = "/platform"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/bookkeeping-nigeria"
  to = "/bookkeeping-nigeria.html"
  status = 200

[[redirects]]
  from = "/bookkeeping-us"
  to = "/bookkeeping-us.html"
  status = 200

[[redirects]]
  from = "/bookkeeping-uk"
  to = "/bookkeeping-uk.html"
  status = 200

[[redirects]]
  from = "/bookkeeping-australia"
  to = "/bookkeeping-australia.html"
  status = 200

[[redirects]]
  from = "/bookkeeping-canada"
  to = "/bookkeeping-canada.html"
  status = 200
