begin;
create schema if not exists private;
create table if not exists public.trb_growth_config(id boolean primary key default true check(id),monthly_client_target integer not null default 100,include_bookslite boolean not null default true,target_markets jsonb not null default '["Nigeria","United States","Canada","United Kingdom","Australia"]',organic_only boolean not null default true,active boolean not null default true,updated_at timestamptz not null default now());
insert into public.trb_growth_config(id) values(true) on conflict(id) do nothing;
create table if not exists public.trb_growth_monthly(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,month_start date not null,target_clients integer not null default 100,new_clients integer not null default 0,managed_clients integer not null default 0,bookslite_clients integer not null default 0,new_leads integer not null default 0,qualified_leads integer not null default 0,quotes_created integer not null default 0,won_sales integer not null default 0,paid_invoices integer not null default 0,revenue numeric not null default 0,target_attainment numeric not null default 0,pace_required numeric not null default 0,updated_at timestamptz not null default now(),unique(owner_id,month_start));
create table if not exists public.trb_growth_actions(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,employee_id text not null references public.ai_employees(id),action_type text not null,channel text,status text not null default 'Queued',scheduled_for timestamptz,completed_at timestamptz,result_summary text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.trb_growth_reports(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,report_date date not null default current_date,period_type text not null default 'daily',employee_id text references public.ai_employees(id),report_title text not null,summary text not null,metrics jsonb not null default '{}'::jsonb,blockers jsonb not null default '[]'::jsonb,next_actions jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
alter table public.leads add column if not exists country text;
alter table public.clients add column if not exists country text;
alter table public.public_lead_intake add column if not exists country text;
create or replace function private.sync_client_country_from_lead() returns trigger language plpgsql security definer set search_path=public,private as $$begin if new.source_lead_id is not null and new.country is null then select country into new.country from public.leads where id=new.source_lead_id; end if; return new; end;$$;
drop trigger if exists trg_sync_client_country_from_lead on public.clients;
create trigger trg_sync_client_country_from_lead before insert or update of source_lead_id,country on public.clients for each row execute function private.sync_client_country_from_lead();
revoke all on function private.sync_client_country_from_lead() from public,anon,authenticated;
alter table public.trb_growth_config enable row level security;drop policy if exists trb_team_growth_config on public.trb_growth_config;create policy trb_team_growth_config on public.trb_growth_config for select to authenticated using(public.trb_business_owner_id() is not null);
alter table public.trb_growth_monthly enable row level security;alter table public.trb_growth_actions enable row level security;alter table public.trb_growth_reports enable row level security;
grant select on public.trb_growth_config to authenticated;grant select,insert,update,delete on public.trb_growth_monthly to authenticated;grant select,insert,update,delete on public.trb_growth_actions to authenticated;grant select,insert,update,delete on public.trb_growth_reports to authenticated;
drop policy if exists trb_team_growth_monthly on public.trb_growth_monthly;drop policy if exists trb_team_growth_actions on public.trb_growth_actions;drop policy if exists trb_team_growth_reports on public.trb_growth_reports;
create policy trb_team_growth_monthly on public.trb_growth_monthly for all to authenticated using(owner_id=public.trb_business_owner_id()) with check(owner_id=public.trb_business_owner_id());
create policy trb_team_growth_actions on public.trb_growth_actions for all to authenticated using(owner_id=public.trb_business_owner_id()) with check(owner_id=public.trb_business_owner_id());
create policy trb_team_growth_reports on public.trb_growth_reports for all to authenticated using(owner_id=public.trb_business_owner_id()) with check(owner_id=public.trb_business_owner_id());
create or replace function private.run_trb_growth_engine() returns void language plpgsql security definer set search_path=public,private as $$
declare owner uuid;ms date:=date_trunc('month',current_date)::date;target integer;nc integer;mc integer;bc integer;nl integer;ql integer;quotes integer;won integer;paid integer;rev numeric;pace numeric;attain numeric;
begin
select owner_id into owner from public.profile order by updated_at desc limit 1;if owner is null then return;end if;
select monthly_client_target into target from public.trb_growth_config where id=true and active=true;target:=coalesce(target,100);
select count(*) into nc from public.clients where owner_id=owner and created_at>=ms and created_at<(ms+interval '1 month');
select count(*) into mc from public.clients where owner_id=owner and access_type='managed_client' and created_at>=ms and created_at<(ms+interval '1 month');
select count(*) into bc from public.clients where owner_id=owner and access_type='bookslite' and created_at>=ms and created_at<(ms+interval '1 month');
select count(*) into nl from public.leads where owner_id=owner and created_at>=ms and created_at<(ms+interval '1 month');
select count(*) into ql from public.leads where owner_id=owner and stage in('Qualified','Quoted','Won') and created_at>=ms and created_at<(ms+interval '1 month');
select count(*) into quotes from public.sales_quotes where owner_id=owner and created_at>=ms and created_at<(ms+interval '1 month');
select count(*) into won from public.sales_quotes where owner_id=owner and status='Won' and created_at>=ms and created_at<(ms+interval '1 month');
select count(*),coalesce(sum(amount),0) into paid,rev from public.invoices where owner_id=owner and status='Paid' and paid_date>=ms and paid_date<(ms+interval '1 month');
pace:=greatest(0,round((target-nc)::numeric/greatest(1,(extract(day from(ms+interval '1 month - 1 day'))::integer-extract(day from current_date)::integer+1)),2));attain:=round((nc::numeric/nullif(target,0))*100,2);
insert into public.trb_growth_monthly(owner_id,month_start,target_clients,new_clients,managed_clients,bookslite_clients,new_leads,qualified_leads,quotes_created,won_sales,paid_invoices,revenue,target_attainment,pace_required) values(owner,ms,target,nc,mc,bc,nl,ql,quotes,won,paid,rev,attain,pace) on conflict(owner_id,month_start) do update set target_clients=excluded.target_clients,new_clients=excluded.new_clients,managed_clients=excluded.managed_clients,bookslite_clients=excluded.bookslite_clients,new_leads=excluded.new_leads,qualified_leads=excluded.qualified_leads,quotes_created=excluded.quotes_created,won_sales=excluded.won_sales,paid_invoices=excluded.paid_invoices,revenue=excluded.revenue,target_attainment=excluded.target_attainment,pace_required=excluded.pace_required,updated_at=now();
end;$$;
revoke all on function private.run_trb_growth_engine() from public,anon,authenticated;
create extension if not exists pg_cron;
select cron.schedule('trb-growth-engine-6h','0 */6 * * *','select private.run_trb_growth_engine();');
commit;